export const data = [
    { length: 6, word: "Kernel", description: "The core manager of the OS that bridges software and hardware.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Thread", description: "The smallest sequence of programmed instructions managed by a scheduler.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Signal", description: "An asynchronous notification sent to a process to notify it of an event.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Paging", description: "Memory management that swaps data between RAM and storage in fixed blocks.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Daemon", description: "A background process that runs without direct user interaction.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 5, word: "Mutex", description: "A locking mechanism used to sync access to a shared resource.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 5, word: "Shell", description: "The command-line interface used to interact with the OS kernel.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Subnet", description: "A logical subdivision of an IP network to improve traffic efficiency.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Packet", description: "A formatted unit of data carried by a packet-switched network.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Socket", description: "One endpoint of a two-way communication link between two programs.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Schema", description: "The formal blueprint or structure that defines a database.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Normal", description: "The process of organizing data to reduce redundancy (e.g., 1NF, 2NF).", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Buffer", description: "Temporary storage area used to hold data being moved between places.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 5, word: "Index", description: "A data structure that improves the speed of data retrieval operations.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 5, word: "Shard", description: "A horizontal partition of data in a database or search engine.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Commit", description: "The operation that saves all changes made during a transaction.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 5, word: "NoSQL", description: "A non-tabular database for flexible, high-scale data storage.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Cursor", description: "A control structure that enables traversal over database records.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Atomic", description: "The 'A' in ACID: ensures a transaction happens entirely or not at all.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 5, word: "Query", description: "A request for data or information from a database table.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Linear", description: "Regression type that fits a straight line to data points ($y = mx + c$).", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Tensor", description: "A multi-dimensional array used as the primary data unit in Deep Learning.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 5, word: "Epoch", description: "One complete pass of the entire training dataset through the model.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Vector", description: "A quantity with both magnitude and direction; an array of features.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Scalar", description: "A single numerical value, as opposed to a vector or matrix.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 5, word: "Layer", description: "A collection of neurons in a neural network that processes inputs.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Forest", description: "An ensemble of decision trees used for robust classification.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Weight", description: "The learnable parameter that adjusts the strength of a signal in AI.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Matrix", description: "A rectangular grid of numbers used for linear transformations.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Neuron", description: "A mathematical function that mimics a biological brain cell in AI.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Prisma", description: "A modern ORM used to map database schemas to type-safe code.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Docker", description: "A platform for packaging apps into portable, isolated containers.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Vercel", description: "A platform for deploying frontend frameworks and static sites.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Strapi", description: "A headless CMS that allows you to manage content via an API.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 5, word: "Redux", description: "A predictable state container for managing JavaScript app data.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 5, word: "Axios", description: "A promise-based HTTP client used to fetch data from APIs.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Framer", description: "A library for creating complex, declarative animations in React.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 5, word: "Figma", description: "A collaborative web-based tool for UI/UX design and prototyping.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Github", description: "The primary hosting service for version control and collaboration.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 7, word: "Postman", description: "A tool for testing APIs by sending requests and viewing responses.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 5, word: "Stack", description: "A LIFO data structure where the last item in is the first out.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 5, word: "Queue", description: "A FIFO data structure where the first item in is the first out.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Binary", description: "A base-2 number system; also a search algorithm that splits data.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 7, word: "Hashing", description: "Mapping data of arbitrary size to a fixed-size value.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Tarjan", description: "An algorithm used to find strongly connected components in a graph.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 5, word: "Splay", description: "A self-adjusting search tree that brings recent items to the root.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 6, word: "Greedy", description: "An algorithm strategy that makes the best local choice at each step.", difficulty: "medium", currentWord: false, previousWord: false },
    { length: 6, word: "Branch", description: "A parallel version of a repository, used to develop features safely.", difficulty: "easy", currentWord: false, previousWord: false },
    { length: 6, word: "Rebase", description: "The Git process of moving a sequence of commits to a new base.", difficulty: "hard", currentWord: false, previousWord: false },
    { length: 7, word: "Express", description: "A minimal web framework for building servers in Node.js.", difficulty: "medium", currentWord: false, previousWord: false }
];

export const prevUsed = [];